# TALLER 2B MATRIZ INVERSA - DESCOMPOSICIÓN LU

**Nombre:** Camila Caicedo

**Grupo:** GR1CC

**Fecha:** 13/01/2026

**Enlace al repositorio:** https://github.com/dxcam/TalleresMetodosNumericos.git

**1. Para las siguientes matrices encontrar la matriz inversa:**

In [1]:
# ----------------------------- logging --------------------------
import logging
from sys import stdout
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

[01-13 20:22:49][INFO] 2026-01-13 20:22:49.617819


In [2]:
%load_ext autoreload

In [5]:
import numpy as np


# ####################################################################
def gauss_jordan(A: np.ndarray) -> np.ndarray:
    """Realiza la eliminación de Gauss-Jordan

    ## Parameters

    ``A``: matriz del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(k), donde n es el número de incógnitas.

    ## Return

    ``A``: matriz reducida por filas.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)
    n = A.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        # for j in range(i + 1, n): # Eliminación gaussiana
        for j in range(n):  # Gauss-Jordan
            if j == i:
                continue  # skip pivot row

            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

            # dividir para la diagonal
        A[i, :] = A[i, :] / A[i, i]

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

        print(f"\n{A}")
    # # --- Sustitución hacia atrás
    # solucion = np.zeros(n)
    # solucion[n - 1] = A[n - 1, n] / A[n - 1, n - 1]

    # for i in range(n - 2, -1, -1):
    #     suma = 0
    #     for j in range(i + 1, n):
    #         suma += A[i, j] * solucion[j]
    #     solucion[i] = (A[i, n] - suma) / A[i, i]

    return A

## Ejercicio 1

In [3]:
%autoreload 2
from src import eliminacion_gaussiana

[01-13 20:23:57][INFO] 2026-01-13 20:23:57.143664


In [6]:
A = [[1, 3, 4], [2, 1, 3], [4, 2, 1]]

In [7]:
from pprint import pprint

pprint(A)
gauss_jordan(A)

[[1, 3, 4], [2, 1, 3], [4, 2, 1]]
[01-13 20:25:03][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 20:25:04][INFO] 
[[ 1.  0.  1.]
 [-0.  1.  1.]
 [ 0.  0. -5.]]
[01-13 20:25:04][INFO] 
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]


array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [-0., -0.,  1.]])

In [8]:
# Poner matriz identidad a la derecha
n = len(A)
A_aug = np.hstack((A, np.eye(n)))
A_aug

array([[1., 3., 4., 1., 0., 0.],
       [2., 1., 3., 0., 1., 0.],
       [4., 2., 1., 0., 0., 1.]])

In [9]:
np.vstack((A, np.eye(n)))

array([[1., 3., 4.],
       [2., 1., 3.],
       [4., 2., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
_m_inv = gauss_jordan(A_aug)
_m_inv

[01-13 20:26:45][INFO] 
[[  1.   3.   4.   1.   0.   0.]
 [  0.  -5.  -5.  -2.   1.   0.]
 [  0. -10. -15.  -4.   0.   1.]]
[01-13 20:26:45][INFO] 
[[ 1.   0.   1.  -0.2  0.6  0. ]
 [-0.   1.   1.   0.4 -0.2 -0. ]
 [ 0.   0.  -5.   0.  -2.   1. ]]
[01-13 20:26:45][INFO] 
[[ 1.   0.   0.  -0.2  0.2  0.2]
 [-0.   1.   0.   0.4 -0.6  0.2]
 [-0.  -0.   1.  -0.   0.4 -0.2]]


array([[ 1. ,  0. ,  0. , -0.2,  0.2,  0.2],
       [-0. ,  1. ,  0. ,  0.4, -0.6,  0.2],
       [-0. , -0. ,  1. , -0. ,  0.4, -0.2]])

In [11]:
_m_inv[:, n:]

array([[-0.2,  0.2,  0.2],
       [ 0.4, -0.6,  0.2],
       [-0. ,  0.4, -0.2]])

# Comprobando respuesta

In [12]:
np.linalg.inv(np.array(A))

array([[-0.2,  0.2,  0.2],
       [ 0.4, -0.6,  0.2],
       [ 0. ,  0.4, -0.2]])

## Ejercicio 2

In [14]:
A = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]

In [15]:
from pprint import pprint

pprint(A)
gauss_jordan(A)

[[1, 2, 3], [0, 1, 4], [5, 6, 0]]
[01-13 20:34:27][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 20:34:27][INFO] 
[[ 1.  0. -5.]
 [ 0.  1.  4.]
 [ 0.  0.  1.]]
[01-13 20:34:27][INFO] 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# Poner matriz identidad a la derecha
n = len(A)
A_aug = np.hstack((A, np.eye(n)))
A_aug

array([[1., 2., 3., 1., 0., 0.],
       [0., 1., 4., 0., 1., 0.],
       [5., 6., 0., 0., 0., 1.]])

In [17]:
np.vstack((A, np.eye(n)))

array([[1., 2., 3.],
       [0., 1., 4.],
       [5., 6., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
_m_inv = gauss_jordan(A_aug)
_m_inv

[01-13 20:34:40][INFO] 
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   4.   0.   1.   0.]
 [  0.  -4. -15.  -5.   0.   1.]]
[01-13 20:34:40][INFO] 
[[ 1.  0. -5.  1. -2.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0.  1. -5.  4.  1.]]
[01-13 20:34:40][INFO] 
[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


array([[  1.,   0.,   0., -24.,  18.,   5.],
       [  0.,   1.,   0.,  20., -15.,  -4.],
       [  0.,   0.,   1.,  -5.,   4.,   1.]])

In [19]:
_m_inv[:, n:]

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

# Comprobando respuesta

In [21]:
np.linalg.inv(np.array(A))

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

## Ejercicio 3

In [22]:
A = [[4, 2, 1], [2, 1, 3], [1, 3, 4]]

In [23]:
from pprint import pprint

pprint(A)
gauss_jordan(A)

[[4, 2, 1], [2, 1, 3], [1, 3, 4]]
[01-13 20:37:49][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 20:37:49][INFO] 
[[ 1.  0.  1.]
 [-0.  1.  1.]
 [ 0.  0. -5.]]
[01-13 20:37:49][INFO] 
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]


array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [-0., -0.,  1.]])

In [24]:
# Poner matriz identidad a la derecha
n = len(A)
A_aug = np.hstack((A, np.eye(n)))
A_aug

array([[4., 2., 1., 1., 0., 0.],
       [2., 1., 3., 0., 1., 0.],
       [1., 3., 4., 0., 0., 1.]])

In [25]:
np.vstack((A, np.eye(n)))

array([[4., 2., 1.],
       [2., 1., 3.],
       [1., 3., 4.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
_m_inv = gauss_jordan(A_aug)
_m_inv

[01-13 20:37:59][INFO] 
[[  1.   3.   4.   0.   0.   1.]
 [  0.  -5.  -5.   0.   1.  -2.]
 [  0. -10. -15.   1.   0.  -4.]]
[01-13 20:37:59][INFO] 
[[ 1.   0.   1.   0.   0.6 -0.2]
 [-0.   1.   1.  -0.  -0.2  0.4]
 [ 0.   0.  -5.   1.  -2.   0. ]]
[01-13 20:37:59][INFO] 
[[ 1.   0.   0.   0.2  0.2 -0.2]
 [-0.   1.   0.   0.2 -0.6  0.4]
 [-0.  -0.   1.  -0.2  0.4 -0. ]]


array([[ 1. ,  0. ,  0. ,  0.2,  0.2, -0.2],
       [-0. ,  1. ,  0. ,  0.2, -0.6,  0.4],
       [-0. , -0. ,  1. , -0.2,  0.4, -0. ]])

In [27]:
_m_inv[:, n:]

array([[ 0.2,  0.2, -0.2],
       [ 0.2, -0.6,  0.4],
       [-0.2,  0.4, -0. ]])

# Comprobando respuesta

In [28]:
np.linalg.inv(np.array(A))

array([[ 0.2,  0.2, -0.2],
       [ 0.2, -0.6,  0.4],
       [-0.2,  0.4,  0. ]])

## Ejercicio 4

In [29]:
A = [[2, 4, 6, 1], [4, 7, 5, -6], [2, 5, 18, 10], [6, 12, 38, 16]]

In [30]:
from pprint import pprint

pprint(A)
gauss_jordan(A)

[[2, 4, 6, 1], [4, 7, 5, -6], [2, 5, 18, 10], [6, 12, 38, 16]]
[01-13 20:38:40][INFO] 
[[ 1.   2.   3.   0.5]
 [ 0.  -1.  -7.  -8. ]
 [ 0.   1.  12.   9. ]
 [ 0.   0.  20.  13. ]]
[01-13 20:38:40][INFO] 
[[  1.    0.  -11.  -15.5]
 [ -0.    1.    7.    8. ]
 [  0.    0.    5.    1. ]
 [  0.    0.   20.   13. ]]
[01-13 20:38:40][INFO] 
[[  1.    0.    0.  -13.3]
 [ -0.    1.    0.    6.6]
 [  0.    0.    1.    0.2]
 [  0.    0.    0.    9. ]]
[01-13 20:38:40][INFO] 
[[ 1.  0.  0.  0.]
 [-0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


array([[ 1.,  0.,  0.,  0.],
       [-0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [31]:
# Poner matriz identidad a la derecha
n = len(A)
A_aug = np.hstack((A, np.eye(n)))
A_aug

array([[ 2.,  4.,  6.,  1.,  1.,  0.,  0.,  0.],
       [ 4.,  7.,  5., -6.,  0.,  1.,  0.,  0.],
       [ 2.,  5., 18., 10.,  0.,  0.,  1.,  0.],
       [ 6., 12., 38., 16.,  0.,  0.,  0.,  1.]])

In [32]:
np.vstack((A, np.eye(n)))

array([[ 2.,  4.,  6.,  1.],
       [ 4.,  7.,  5., -6.],
       [ 2.,  5., 18., 10.],
       [ 6., 12., 38., 16.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [33]:
_m_inv = gauss_jordan(A_aug)
_m_inv

[01-13 20:38:54][INFO] 
[[ 1.   2.   3.   0.5  0.5  0.   0.   0. ]
 [ 0.  -1.  -7.  -8.  -2.   1.   0.   0. ]
 [ 0.   1.  12.   9.  -1.   0.   1.   0. ]
 [ 0.   0.  20.  13.  -3.   0.   0.   1. ]]
[01-13 20:38:54][INFO] 
[[  1.    0.  -11.  -15.5  -3.5   2.    0.    0. ]
 [ -0.    1.    7.    8.    2.   -1.   -0.   -0. ]
 [  0.    0.    5.    1.   -3.    1.    1.    0. ]
 [  0.    0.   20.   13.   -3.    0.    0.    1. ]]
[01-13 20:38:54][INFO] 
[[  1.    0.    0.  -13.3 -10.1   4.2   2.2   0. ]
 [ -0.    1.    0.    6.6   6.2  -2.4  -1.4  -0. ]
 [  0.    0.    1.    0.2  -0.6   0.2   0.2   0. ]
 [  0.    0.    0.    9.    9.   -4.   -4.    1. ]]
[01-13 20:38:54][INFO] 
[[ 1.          0.          0.          0.          3.2        -1.71111111
  -3.71111111  1.47777778]
 [-0.          1.          0.          0.         -0.4         0.53333333
   1.53333333 -0.73333333]
 [ 0.          0.          1.          0.         -0.8         0.28888889
   0.28888889 -0.02222222]
 [ 0.          0. 

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  3.2       ,
        -1.71111111, -3.71111111,  1.47777778],
       [-0.        ,  1.        ,  0.        ,  0.        , -0.4       ,
         0.53333333,  1.53333333, -0.73333333],
       [ 0.        ,  0.        ,  1.        ,  0.        , -0.8       ,
         0.28888889,  0.28888889, -0.02222222],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  1.        ,
        -0.44444444, -0.44444444,  0.11111111]])

In [34]:
_m_inv[:, n:]

array([[ 3.2       , -1.71111111, -3.71111111,  1.47777778],
       [-0.4       ,  0.53333333,  1.53333333, -0.73333333],
       [-0.8       ,  0.28888889,  0.28888889, -0.02222222],
       [ 1.        , -0.44444444, -0.44444444,  0.11111111]])

# Comprobando respuesta

In [35]:
np.linalg.inv(np.array(A))

array([[ 3.2       , -1.71111111, -3.71111111,  1.47777778],
       [-0.4       ,  0.53333333,  1.53333333, -0.73333333],
       [-0.8       ,  0.28888889,  0.28888889, -0.02222222],
       [ 1.        , -0.44444444, -0.44444444,  0.11111111]])

**2. Calcule la descomposición LU para estas matrices y encuentre la solución para estos vectores de valores independientes b.**

In [36]:
# ####################################################################
def descomposicion_LU(A: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Realiza la descomposición LU de una matriz cuadrada A.
    [IMPORTANTE] No se realiza pivoteo.

    ## Parameters

    ``A``: matriz cuadrada de tamaño n-by-n.

    ## Return

    ``L``: matriz triangular inferior.

    ``U``: matriz triangular superior. Se obtiene de la matriz ``A`` después de aplicar la eliminación gaussiana.
    """

    A = np.array(
        A, dtype=float
    )  # convertir en float, porque si no, puede convertir como entero

    assert A.shape[0] == A.shape[1], "La matriz A debe ser cuadrada."
    n = A.shape[0]

    L = np.zeros((n, n), dtype=float)

    for i in range(0, n):  # loop por columna

        # --- deterimnar pivote
        if A[i, i] == 0:
            raise ValueError("No existe solución única.")

        # --- Eliminación: loop por fila
        L[i, i] = 1
        for j in range(i + 1, n):
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

            L[j, i] = m

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

    return L, A

In [37]:
# ####################################################################
def resolver_LU(L: np.ndarray, U: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante la descomposición LU.

    ## Parameters

    ``L``: matriz triangular inferior.

    ``U``: matriz triangular superior.

    ``b``: vector de términos independientes.

    ## Return

    ``solucion``: vector con la solución del sistema de ecuaciones lineales.

    """

    n = L.shape[0]

    # --- Sustitución hacia adelante
    logging.info("Sustitución hacia adelante")

    y = np.zeros((n, 1), dtype=float)

    y[0] = b[0] / L[0, 0]

    for i in range(1, n):
        suma = 0
        for j in range(i):
            suma += L[i, j] * y[j]
        y[i] = (b[i] - suma) / L[i, i]

    logging.info(f"y = \n{y}")

    # --- Sustitución hacia atrás
    logging.info("Sustitución hacia atrás")
    sol = np.zeros((n, 1), dtype=float)

    sol[-1] = y[-1] / U[-1, -1]

    for i in range(n - 2, -1, -1):
        logging.info(f"i = {i}")
        suma = 0
        for j in range(i + 1, n):
            suma += U[i, j] * sol[j]
        logging.info(f"suma = {suma}")
        logging.info(f"U[i, i] = {U[i, i]}")
        logging.info(f"y[i] = {y[i]}")
        sol[i] = (y[i] - suma) / U[i, i]

    logging.debug(f"x = \n{sol}")
    return sol

## Ejercicio 1

In [103]:
A = [[1, 3, 4], [2, 1, 3], [4, 2, 1]]

In [104]:
b = [[1], [2], [4]]

In [105]:
print("Descomposición LU")
L1, U1 = descomposicion_LU(A)


Descomposición LU
[01-13 21:34:03][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 21:34:03][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 21:34:03][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]


In [106]:
print("\nL=", L1)
print("\nU=", U1)


L= [[1. 0. 0.]
 [2. 1. 0.]
 [4. 2. 1.]]

U= [[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]


In [107]:
print("Ly = b")
print("Cálculo del vector y:")
print("Sustitución hacia atrás (Ux = y)")
print("Solución del sistema:")
x1 = resolver_LU(L1, U1, b)

Ly = b
Cálculo del vector y:
Sustitución hacia atrás (Ux = y)
Solución del sistema:
[01-13 21:34:11][INFO] Sustitución hacia adelante
[01-13 21:34:11][INFO] y = 
[[1.]
 [0.]
 [0.]]
[01-13 21:34:11][INFO] Sustitución hacia atrás
[01-13 21:34:11][INFO] i = 1
[01-13 21:34:11][INFO] suma = [0.]
[01-13 21:34:11][INFO] U[i, i] = -5.0
[01-13 21:34:11][INFO] y[i] = [0.]
[01-13 21:34:11][INFO] i = 0
[01-13 21:34:11][INFO] suma = [0.]
[01-13 21:34:11][INFO] U[i, i] = 1.0
[01-13 21:34:11][INFO] y[i] = [1.]


In [108]:
print("\nSolución:")
print(x1)


Solución:
[[ 1.]
 [-0.]
 [-0.]]


## Ejercicio 2

In [109]:
A = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]

In [110]:
b = [[2], [-5], [2]]

In [111]:
print("Descomposición LU")
L2, U2 = descomposicion_LU(A)

Descomposición LU
[01-13 21:34:24][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 21:34:24][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 21:34:24][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]


In [112]:
print("\nL=", L2)
print("\nU=", U2)


L= [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 5. -4.  1.]]

U= [[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]


In [113]:
print("Ly = b")
print("Cálculo del vector y:")
print("Sustitución hacia atrás (Ux = y)")
print("Solución del sistema:")
x2 = resolver_LU(L1, U1, b)

Ly = b
Cálculo del vector y:
Sustitución hacia atrás (Ux = y)
Solución del sistema:
[01-13 21:34:30][INFO] Sustitución hacia adelante
[01-13 21:34:30][INFO] y = 
[[ 2.]
 [-9.]
 [12.]]
[01-13 21:34:30][INFO] Sustitución hacia atrás
[01-13 21:34:30][INFO] i = 1
[01-13 21:34:30][INFO] suma = [12.]
[01-13 21:34:30][INFO] U[i, i] = -5.0
[01-13 21:34:30][INFO] y[i] = [-9.]
[01-13 21:34:30][INFO] i = 0
[01-13 21:34:30][INFO] suma = [3.]
[01-13 21:34:30][INFO] U[i, i] = 1.0
[01-13 21:34:30][INFO] y[i] = [2.]


In [114]:
print("\nSolución:")
print(x2)


Solución:
[[-1. ]
 [ 4.2]
 [-2.4]]


## Ejercicio 3

In [95]:
A = [[4, 2, 1], [2, 1, 3], [1, 3, 4]]

In [96]:
b = [[7], [8], [-1]]

In [97]:
print("Descomposición LU")
L3, U3 = descomposicion_LU(A)

Descomposición LU
[01-13 21:32:48][INFO] 
[[4.   2.   1.  ]
 [0.   0.   2.5 ]
 [0.   2.5  3.75]]


ValueError: No existe solución única.

- **Corrección:** Después de eliminar la columna 1, el segundo pivote queda en cero, y como NO hay pivoteo, el algoritmo debe detenerse. Dado que el algoritmo implementado no considera pivoteo, fue necesario reordenar manualmente las filas de la matriz del sistema para evitar pivotes nulos y permitir la factorización LU.

In [115]:
A3 = np.array([
    [4, 2, 1],
    [1, 3, 4],
    [2, 1, 3]
], dtype=float)

b3 = np.array([7, -1, 8], dtype=float).reshape(-1, 1)


In [116]:
print("Descomposición LU")
L3, U3 = descomposicion_LU(A3)

Descomposición LU
[01-13 21:40:02][INFO] 
[[4.   2.   1.  ]
 [0.   2.5  3.75]
 [0.   0.   2.5 ]]
[01-13 21:40:02][INFO] 
[[4.   2.   1.  ]
 [0.   2.5  3.75]
 [0.   0.   2.5 ]]
[01-13 21:40:02][INFO] 
[[4.   2.   1.  ]
 [0.   2.5  3.75]
 [0.   0.   2.5 ]]


In [98]:
print("\nL=", L3)
print("\nU=", U3)


L= [[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1. -1.  1.  0.]
 [ 3. -0.  4.  1.]]

U= [[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]


In [117]:
print("Ly = b")
print("Cálculo del vector y:")
print("Sustitución hacia atrás (Ux = y)")
print("Solución del sistema:")
x3 = resolver_LU(L3, U3, b)

Ly = b
Cálculo del vector y:
Sustitución hacia atrás (Ux = y)
Solución del sistema:
[01-13 21:40:36][INFO] Sustitución hacia adelante
[01-13 21:40:36][INFO] y = 
[[ 2. ]
 [-5.5]
 [ 1. ]]
[01-13 21:40:36][INFO] Sustitución hacia atrás
[01-13 21:40:36][INFO] i = 1
[01-13 21:40:36][INFO] suma = [1.5]
[01-13 21:40:36][INFO] U[i, i] = 2.5
[01-13 21:40:36][INFO] y[i] = [-5.5]
[01-13 21:40:36][INFO] i = 0
[01-13 21:40:36][INFO] suma = [-5.2]
[01-13 21:40:36][INFO] U[i, i] = 4.0
[01-13 21:40:36][INFO] y[i] = [2.]


In [118]:
print("\nSolución:")
print(x3)


Solución:
[[ 1.8]
 [-2.8]
 [ 0.4]]


## Ejercicio 4

In [85]:
A = [[2, 4, 6, 1], [4, 7, 5, -6], [2, 5, 18, 10], [6, 12, 38, 16]]

In [86]:
b = [[1], [2], [4], [5]]

In [88]:
print("Descomposición LU")
L4, U4 = descomposicion_LU(A)

Descomposición LU
[01-13 21:30:49][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 21:30:49][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 21:30:49][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 21:30:49][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]


In [90]:
print("\nL=", L4)
print("\nU=", U4)


L= [[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1. -1.  1.  0.]
 [ 3. -0.  4.  1.]]

U= [[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]


In [91]:
print("Ly = b")
print("Cálculo del vector y:")
print("Sustitución hacia atrás (Ux = y)")
print("Solución del sistema:")
x4 = resolver_LU(L4, U4, b)

Ly = b
Cálculo del vector y:
Sustitución hacia atrás (Ux = y)
Solución del sistema:
[01-13 21:31:45][INFO] Sustitución hacia adelante
[01-13 21:31:45][INFO] y = 
[[  1.]
 [  0.]
 [  3.]
 [-10.]]
[01-13 21:31:45][INFO] Sustitución hacia atrás
[01-13 21:31:45][INFO] i = 2
[01-13 21:31:45][INFO] suma = [-1.11111111]
[01-13 21:31:45][INFO] U[i, i] = 5.0
[01-13 21:31:45][INFO] y[i] = [3.]
[01-13 21:31:45][INFO] i = 1
[01-13 21:31:45][INFO] suma = [3.13333333]
[01-13 21:31:45][INFO] U[i, i] = -1.0
[01-13 21:31:45][INFO] y[i] = [0.]
[01-13 21:31:45][INFO] i = 0
[01-13 21:31:45][INFO] suma = [16.35555556]
[01-13 21:31:45][INFO] U[i, i] = 2.0
[01-13 21:31:45][INFO] y[i] = [1.]


In [92]:
print("\nSolución:")
print(x4)


Solución:
[[-7.67777778]
 [ 3.13333333]
 [ 0.82222222]
 [-1.11111111]]
